server:
  port: 8080

spring:
  application:
    name: SanguiBlog-server
  datasource:
    url: jdbc:mysql://localhost:3306/sanguiblog_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: ${DB_USERNAME:${SPRING_DATASOURCE_USERNAME:root}}
    password: ${DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD:}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    default-property-inclusion: non_null

jwt:
  secret: ${JWT_SECRET:${SPRING_JWT_SECRET:?JWT_SECRET (or SPRING_JWT_SECRET) is required}}
  expiration-minutes: 180
  issuer: sangui-blog

springdoc:
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
  api-docs:
    enabled: false
    path: /api-docs

logging:
  level:
    com.sangui.sanguiblog: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

storage:
#    base-path: ${STORAGE_BASE_PATH:uploads}
    base-path: D:\02-WorkSpace\02-Java\SanguiBlog\uploads
site:
  version: "V1.3.92"
#  asset-base-url: http://localhost:8080/uploads
#  asset-base-url: https://nonmature-scraggily-fermin.ngrok-free.dev/uploads
  asset-base-url: https://puristic-david-unsorely.ngrok-free.dev/uploads
  footer:
    year: 2025
    brand: 三桂博客
    icp-number: 浙ICP备2025167176号
    icp-link: https://beian.miit.gov.cn/
    powered-by: Powered by Spring Boot 3 & React 19
